version: '3'

services:
  mautic_web:
    build: .
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST?}
      - MYSQL_PORT=${MYSQL_PORT?}
      - MYSQL_USER=${MYSQL_USER?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME?}
    ports:
      - 80:80
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100