version: '3'

services:
  mautic_web:
    build: .
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST?}
      - MYSQL_PORT=${MYSQL_PORT?}
      - MYSQL_USER=${MYSQL_USER?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME?}
      # TODO: https://github.com/mautic/docker-mautic/pull/265
      # NOTE: change config/local.php for workaround
      - MAUTIC_MESSENGER_DSN_EMAIL=${MAUTIC_MESSENGER_DSN_EMAIL?}
      - MAUTIC_MESSENGER_DSN_HIT=${MAUTIC_MESSENGER_DSN_HIT?}
    ports:
      - 80:80
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100